# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: block
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: DonationTracker
    address:
    - 0x7167C5B16dA69Ba6C0Ba00710Bd828B552486bD9
    handler: src/EventHandlers.ts
    events:
    - event: CampaignCreated(uint256 campaignId, address indexed creator)
    - event: CampaignEnded(uint256 campaignId, address creator, uint256 refundedFee)
    - event: DonationReceived(uint256 campaignId, address indexed donor, uint256 amount)
    - event: ProofUploaded(uint256 campaignId, uint256 withdrawalId, string proofUrl)
    - event: WithdrawalMade(uint256 campaignId, address indexed admin, uint256 amount)
rollback_on_reorg: false
